services:
  catalog-registry:
    container_name: "catalog-registry"
    image: node:18.12
    command: >
      sh -c "cd /usr/src/app &&
             npm install -g pnpm &&
             pnpm install --ignore-scripts &&
             pnpm run dev"
    ports:
      - "${CATALOG_REGISTRY_PORT}:3000"
    env_file:
      - .env
    volumes:
      - ${CATALOG_REGISTRY_PATH}:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      MONGO_HOST: "db"
      MONGO_PORT: "27017"
      MONGO_DATABASE: "${CATALOG_REGISTRY_MONGODB}"
    networks:
      - ptx-main
      - db_default

  catalog:
    container_name: "catalog"
    image: node:18.12
    command: >
      sh -c "cp /tmp/.npmrc /root/.npmrc &&
             cd /usr/src/app &&
             npm install -g pnpm &&
             pnpm install --ignore-scripts &&
             pnpm rebuild bcrypt &&
             pnpm run dev"
    ports:
      - "${CATALOG_PORT}:${CATALOG_PORT}"
    env_file:
      - .env
    volumes:
      - ${CATALOG_PATH}:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.npmrc:/tmp/.npmrc:ro
    working_dir: /usr/src/app
    environment:
      MONGO_URI: "mongodb://db:27017/${CATALOG_MONGODB}"
    networks:
      - ptx-main
      - db_default

  consent:
    container_name: "catalog"
    image: node:18.12
    command: >
      sh -c "cd /usr/src/app &&
             npm install -g pnpm &&
             pnpm install --ignore-scripts &&
             pnpm rebuild bcrypt &&
             pnpm run dev"
    ports:
      - "${CATALOG_PORT}:${CATALOG_PORT}"
    env_file:
      - .env
    volumes:
      - ${CATALOG_PATH}:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.npmrc:/tmp/.npmrc:ro
    working_dir: /usr/src/app
    environment:
      MONGO_URI: "mongodb://db:27017/${CATALOG_MONGODB}"
    networks:
      - ptx-main
      - db_default

  app:
    container_name: "app"
    image: node:18.12
    command: >
      sh -c "cd /usr/src/app &&
             npm install -g pnpm &&
             pnpm install --ignore-scripts &&
             pnpm run dev"
    ports:
      - "${APP_PORT}:5173"
    env_file:
      - .env
    volumes:
      - ${APP_PATH}:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      HOST: "0.0.0.0"
      PORT: "5173"
      NODE_ENV: "development"
      VITE_VISIONSTRUST_API: http://catalog:${CATALOG_PORT}
      VITE_CONTRACT_SERVICE_URL: 
      VITE_REGISTRY_URL: 
      VITE_CONSENT_SERVICE_URL: 
    networks:
      - ptx-main

networks:
  ptx-main:
    driver: bridge
  db_default:
    external: true

volumes:
  mongodb_data:
