# Stage 1: Build & Prepare Data
FROM debian:bullseye-slim AS builder

RUN apt-get update && \
    apt-get install -y gettext dos2unix jq && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy scripts and templates
COPY prepare-seed.sh ./prepare-seed.sh
COPY .env ./.env
COPY images/mongodb-seed/template/ ./images/mongodb-seed/template/

# Make the script executable and convert line endings
RUN chmod +x ./prepare-seed.sh && dos2unix ./prepare-seed.sh

# Stage 2: Final MongoDB Image
FROM mongo

WORKDIR /app

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext && rm -rf /var/lib/apt/lists/*

# Copy the init directory
COPY ./images/mongodb-seed/init/ /init/

# Copy the prepared JSON files
COPY --from=builder /app/images/mongodb-seed/template/ /app/images/mongodb-seed/template/

# Copy the script from the builder stage
COPY --from=builder /app/prepare-seed.sh /app/prepare-seed.sh

# Ensure the script is executable
RUN chmod +x /app/prepare-seed.sh

# Execute the script on container start
CMD ["/bin/bash", "-c", "/app/prepare-seed.sh"]
